"""
Task 4 - FastAPI deployment of the student-performance prediction model.

Run:
    uvicorn main:app --reload --port 8000

Docs (auto-generated by FastAPI):
    http://127.0.0.1:8000/docs
"""
import json
from pathlib import Path
from typing import Literal

import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field, field_validator


# Load model artifacts
ARTIFACT_DIR = Path(__file__).parent / "model_artifacts"

model = joblib.load(ARTIFACT_DIR / "model.joblib")
scaler = joblib.load(ARTIFACT_DIR / "scaler.joblib")
with open(ARTIFACT_DIR / "label_encoders.json") as f:
    label_encoders = json.load(f)
with open(ARTIFACT_DIR / "feature_columns.json") as f:
    feature_cols = json.load(f)

MODEL_VERSION = "1.0.0"

app = FastAPI(
    title="Student Performance Prediction API",
    description="Predicts a student's final exam score (0-100) from study habits and background factors.",
    version=MODEL_VERSION,
)

# Allow the bundled dashboard (or any local frontend) to call this API.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# Request / response schemas with input validation
class StudentFeatures(BaseModel):
    study_hours: float = Field(..., ge=0, le=16, description="Average daily study hours")
    attendance_percent: float = Field(..., ge=0, le=100, description="Class attendance percentage")
    previous_scores: float = Field(..., ge=0, le=100, description="Previous exam score")
    sleep_hours: float = Field(..., ge=0, le=14, description="Average nightly sleep hours")
    extracurricular: Literal["Yes", "No"]
    parental_education: Literal["High School", "Bachelors", "Masters", "PhD"]
    internet_access: Literal["Yes", "No"]

    @field_validator("study_hours", "attendance_percent", "previous_scores", "sleep_hours")
    @classmethod
    def must_be_finite(cls, v):
        if v is None or np.isnan(v) or np.isinf(v):
            raise ValueError("must be a finite number")
        return v

    class Config:
        json_schema_extra = {
            "example": {
                "study_hours": 5.5,
                "attendance_percent": 88.0,
                "previous_scores": 72.0,
                "sleep_hours": 7.0,
                "extracurricular": "Yes",
                "parental_education": "Bachelors",
                "internet_access": "Yes",
            }
        }


class PredictionResponse(BaseModel):
    predicted_final_score: float
    model_version: str
    input_echo: StudentFeatures


class HealthResponse(BaseModel):
    status: str
    model_version: str
    model_type: str


# Helpers
def encode_value(col: str, value: str) -> int:
    mapping = label_encoders[col]
    if value not in mapping:
        raise HTTPException(status_code=422, detail=f"Invalid value '{value}' for {col}. Choices: {list(mapping)}")
    return mapping[value]


def to_feature_row(payload: StudentFeatures) -> pd.DataFrame:
    row = {
        "study_hours": payload.study_hours,
        "attendance_percent": payload.attendance_percent,
        "previous_scores": payload.previous_scores,
        "sleep_hours": payload.sleep_hours,
        "extracurricular": encode_value("extracurricular", payload.extracurricular),
        "parental_education": encode_value("parental_education", payload.parental_education),
        "internet_access": encode_value("internet_access", payload.internet_access),
    }
    return pd.DataFrame([row])[feature_cols]


# Routes
@app.get("/health", response_model=HealthResponse, tags=["meta"])
def health():
    return HealthResponse(
        status="ok",
        model_version=MODEL_VERSION,
        model_type=type(model).__name__,
    )


@app.post("/predict", response_model=PredictionResponse, tags=["prediction"])
def predict(payload: StudentFeatures):
    try:
        X = to_feature_row(payload)
        X_scaled = scaler.transform(X)
        pred = float(model.predict(X_scaled)[0])
        pred = max(0.0, min(100.0, pred))  # clip to valid score range
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"Prediction failed: {exc}")

    return PredictionResponse(predicted_final_score=round(pred, 2), model_version=MODEL_VERSION, input_echo=payload)


# Serve the bundled dashboard at "/"
DASHBOARD_DIR = Path(__file__).parent / "static"
if DASHBOARD_DIR.exists():
    app.mount("/static", StaticFiles(directory=DASHBOARD_DIR), name="static")

    @app.get("/", tags=["meta"])
    def dashboard():
        return FileResponse(DASHBOARD_DIR / "index.html")
